import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, StatusBar } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context'; // Đã sửa dòng này
import { useRouter } from 'expo-router';

export default function AiAssistantScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={styles.safeArea}>
      <StatusBar barStyle="light-content" backgroundColor="#121212" />
      
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.iconBtn}>
          <Text style={styles.iconText}>{'<'}</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.iconBtn}>
          <Text style={styles.iconText}>⚙</Text>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.container} contentContainerStyle={{ paddingBottom: 30 }}>
        
        {/* Translate Section */}
        <Text style={styles.sectionTitle}>Translate</Text>
        
        <View style={styles.grid}>
          <TouchableOpacity style={styles.cardHalf}>
            <Text style={styles.icon}>📄</Text>
            <Text style={styles.cardTitle}>Text translation</Text>
          </TouchableOpacity>
          
          <TouchableOpacity style={styles.cardHalf}>
            <Text style={styles.icon}>🎙️</Text>
            <Text style={styles.cardTitle}>Voice translation</Text>
          </TouchableOpacity>
          
          <TouchableOpacity style={styles.cardHalf}>
            <Text style={styles.icon}>💬</Text>
            <Text style={styles.cardTitle}>Conversation translation</Text>
            <Text style={styles.cardSubtitle}>Multilingual support</Text>
          </TouchableOpacity>
          
          <TouchableOpacity style={styles.cardHalf}>
            <Text style={styles.icon}>🗣️</Text>
            <Text style={styles.cardTitle}>Simultaneous interpretation</Text>
          </TouchableOpacity>
        </View>

        <TouchableOpacity style={styles.cardFull}>
          <Text style={styles.icon}>🗨️</Text>
          <Text style={styles.cardTitle}>Free conversation</Text>
        </TouchableOpacity>

        {/* AI Assistant Section */}
        <Text style={[styles.sectionTitle, { marginTop: 30 }]}>AI assistant</Text>
        
        <View style={styles.aiGrid}>
          <TouchableOpacity style={styles.aiCardLeft}>
            <View style={styles.aiHeaderRow}>
              <Text style={styles.icon}>🤖</Text>
              <View style={{ marginLeft: 12 }}>
                <Text style={styles.cardTitle}>Ai friends</Text>
                <Text style={styles.blueText}>deepseek</Text>
              </View>
            </View>
          </TouchableOpacity>

          <TouchableOpacity style={styles.aiCardRight}>
            <View style={styles.avatarPlaceholder}>
              <Text style={{ fontSize: 35 }}>👩‍🎨</Text>
            </View>
            <Text style={styles.characterText}>Character{"\n"}Selection</Text>
          </TouchableOpacity>
        </View>

        <TouchableOpacity style={styles.cardFull}>
          <Text style={styles.icon}>AI</Text>
          <Text style={styles.cardTitle}>AI conversation</Text>
        </TouchableOpacity>

        {/* Footer */}
        <Text style={styles.footerText}>
          The content is generated by a large model and is prohibited from being used for illegal activities
        </Text>

      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#121212' },
  container: { flex: 1, paddingHorizontal: 20 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10, marginBottom: 20, paddingHorizontal: 20 },
  iconBtn: { padding: 5 },
  iconText: { color: '#FFF', fontSize: 24, fontWeight: 'bold' },
  sectionTitle: { color: '#FFF', fontSize: 18, fontWeight: 'bold', marginBottom: 15 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  cardHalf: { width: '48%', backgroundColor: '#1C1C1E', borderRadius: 15, padding: 20, marginBottom: 15, justifyContent: 'center', alignItems: 'center', minHeight: 120 },
  cardFull: { width: '100%', backgroundColor: '#1C1C1E', borderRadius: 15, padding: 20, marginBottom: 15, flexDirection: 'row', alignItems: 'center' },
  icon: { fontSize: 28, marginBottom: 10, color: '#FFF' },
  cardTitle: { color: '#FFF', fontSize: 15, fontWeight: '600', textAlign: 'center' },
  cardSubtitle: { color: '#888', fontSize: 12, marginTop: 5, textAlign: 'center' },
  aiGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15 },
  aiCardLeft: { width: '65%', backgroundColor: '#1C1C1E', borderRadius: 15, padding: 20, justifyContent: 'center' },
  aiHeaderRow: { flexDirection: 'row', alignItems: 'center' },
  blueText: { color: '#4A90E2', fontSize: 13, fontWeight: 'bold', marginTop: 2 },
  aiCardRight: { width: '31%', backgroundColor: '#1C1C1E', borderRadius: 15, padding: 15, justifyContent: 'center', alignItems: 'center' },
  avatarPlaceholder: { width: 50, height: 50, borderRadius: 25, backgroundColor: '#333', justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  characterText: { color: '#FFF', fontSize: 11, textAlign: 'center', fontWeight: '500' },
  footerText: { color: '#555', fontSize: 10, textAlign: 'center', marginTop: 30, paddingHorizontal: 20, lineHeight: 16 }
});